import { 
  Info, 
  List, 
  PlusCircle, 
  SearchX, 
  Plus, 
  Trash2, 
  Pencil, 
  MapPin, 
  Globe, 
  RefreshCw, 
  Tag, 
  PushPin, 
  Building2, 
  Folder, 
  BarChart3, 
  Calculator, 
  DollarSign, 
  CheckCircle2, 
  Package, 
  ClipboardList, 
  Settings, 
  X, 
  FileText, 
  Lightbulb, 
  Hash, 
  Zap, 
  Triangle, 
  Check, 
  Ban, 
  Search, 
  ArrowLeft, 
  ChevronRight, 
  CreditCard, 
  ShoppingCart, 
  Cpu, 
  FileEdit, 
  User, 
  UserPlus, 
  Key, 
  AlertTriangle, 
  Settings2, 
  Calendar, 
  GitFork, 
  Layers, 
  ClipboardCheck, 
  Truck, 
  History, 
  BadgeCheck, 
  CalendarOff, 
  Sliders, 
  Fingerprint, 
  Link, 
  CornerDownRight, 
  PlusSquare, 
  FolderOff, 
  FilterX, 
  AlertCircle, 
  Users, 
  Factory, 
  UserCog, 
  ShieldCheck, 
  FolderTree, 
  Edit2, 
  Contact, 
  UserSearch, 
  UserCheck, 
  PackageSearch, 
  Store, 
  ArrowRight, 
  LogOut, 
  Bell, 
  Eye, 
  Rocket, 
  Play, 
  PlayCircle, 
  Timer, 
  CheckCircle, 
  XCircle, 
  Send, 
  FileQuestion, 
  Printer, 
  Copy, 
  LayoutDashboard, 
  Layout, 
  Bot, 
  Gauge, 
  Network, 
  ChevronDown, 
  ChevronUp, 
  Mail, 
  Phone, 
  ScanBarcode, 
  ShoppingBasket,
  Terminal,
  FilePlus,
  ExternalLink,
  Filter,
  Badge,
  Tablet,
  BarChart4,
  Sparkles,
  Database,
  Shield,
  Route,
  File,
  LayoutGrid,
  Contact2
} from 'lucide-vue-next'

// Comprehensive mapping for aliases (Material, Slugs) and Direct Component Names
const iconMap: Record<string, any> = {
  // Material Symbols / Aliases
  'info': Info,
  'list_alt': List,
  'add_circle': PlusCircle,
  'search_off': SearchX,
  'add': Plus,
  'delete': Trash2,
  'edit': Pencil,
  'location_on': MapPin,
  'public': Globe,
  'refresh': RefreshCw,
  'sell': Tag,
  'push_pin': PushPin,
  'corporate_fare': Building2,
  'folder': Folder,
  'bar_chart': BarChart3,
  'calculate': Calculator,
  'attach_money': DollarSign,
  'check_circle': CheckCircle,
  'inventory_2': Package,
  'assignment': ClipboardList,
  'settings': Settings,
  'close': X,
  'description': FileText,
  'lightbulb': Lightbulb,
  'numbers': Hash,
  'bolt': Zap,
  'change_history': Triangle,
  'check': Check,
  'block': Ban,
  'search': Search,
  'arrow_back': ArrowLeft,
  'chevron_right': ChevronRight,
  'payments': CreditCard,
  'shopping_cart': ShoppingCart,
  'precision_manufacturing': Factory,
  'edit_note': FileEdit,
  'person': User,
  'person_add': UserPlus,
  'key': Key,
  'warning': AlertTriangle,
  'settings_suggest': Settings2,
  'calendar_today': Calendar,
  'account_tree': GitFork,
  'layers': Layers,
  'category': FolderTree,
  'fact_check': ClipboardCheck,
  'local_shipping': Truck,
  'history_edu': History,
  'badge': BadgeCheck,
  'event': Calendar,
  'event_note': Calendar,
  'event_busy': CalendarOff,
  'domain': Building2,
  'sync': RefreshCw,
  'tune': Sliders,
  'settings_input_component': Cpu,
  'branding_watermark': BadgeCheck,
  'notes': FileText,
  'fingerprint': Fingerprint,
  'link': Link,
  'subdirectory_arrow_right': CornerDownRight,
  'add_box': PlusSquare,
  'folder_off': FolderOff,
  'filter_alt_off': FilterX,
  'error': AlertCircle,
  'groups': Users,
  'manage_accounts': UserCog,
  'admin_panel_settings': ShieldCheck,
  'visibility': Eye,
  'rocket_launch': Rocket,
  'play_arrow': Play,
  'play_circle': PlayCircle,
  'pending_actions': Timer,
  'task_alt': CheckCircle,
  'cancel': XCircle,
  'send': Send,
  'request_quote': FileQuestion,
  'print': Printer,
  'content_copy': Copy,
  'dashboard': LayoutDashboard,
  'smart_toy': Bot,
  'speed': Gauge,
  'settings_ethernet': Network,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'mail': Mail,
  'phone': Phone,
  'barcode_scanner': ScanBarcode,
  'shopping_basket': ShoppingBasket,
  'route': Route,
  'file': File,
  'grid_view': LayoutGrid,
  'contact_2': Contact2,

  // Direct Component Names (Self-mapping)
  'Info': Info,
  'List': List,
  'PlusCircle': PlusCircle,
  'SearchX': SearchX,
  'Plus': Plus,
  'Trash2': Trash2,
  'Pencil': Pencil,
  'MapPin': MapPin,
  'Globe': Globe,
  'RefreshCw': RefreshCw,
  'Tag': Tag,
  'PushPin': PushPin,
  'Building2': Building2,
  'Folder': Folder,
  'BarChart3': BarChart3,
  'Calculator': Calculator,
  'DollarSign': DollarSign,
  'CheckCircle2': CheckCircle2,
  'Package': Package,
  'ClipboardList': ClipboardList,
  'Settings': Settings,
  'X': X,
  'FileText': FileText,
  'Lightbulb': Lightbulb,
  'Hash': Hash,
  'Zap': Zap,
  'Triangle': Triangle,
  'Check': Check,
  'Ban': Ban,
  'Search': Search,
  'ArrowLeft': ArrowLeft,
  'ChevronRight': ChevronRight,
  'CreditCard': CreditCard,
  'ShoppingCart': ShoppingCart,
  'Factory': Factory,
  'FileEdit': FileEdit,
  'User': User,
  'UserPlus': UserPlus,
  'Key': Key,
  'AlertTriangle': AlertTriangle,
  'Settings2': Settings2,
  'Calendar': Calendar,
  'GitFork': GitFork,
  'Layers': Layers,
  'FolderTree': FolderTree,
  'ClipboardCheck': ClipboardCheck,
  'Truck': Truck,
  'History': History,
  'BadgeCheck': BadgeCheck,
  'CalendarOff': CalendarOff,
  'Sliders': Sliders,
  'Cpu': Cpu,
  'Fingerprint': Fingerprint,
  'Link': Link,
  'CornerDownRight': CornerDownRight,
  'PlusSquare': PlusSquare,
  'FolderOff': FolderOff,
  'FilterX': FilterX,
  'AlertCircle': AlertCircle,
  'Users': Users,
  'UserCog': UserCog,
  'ShieldCheck': ShieldCheck,
  'Edit2': Edit2,
  'Contact': Contact,
  'UserSearch': UserSearch,
  'UserCheck': UserCheck,
  'PackageSearch': PackageSearch,
  'Store': Store,
  'ArrowRight': ArrowRight,
  'LogOut': LogOut,
  'Bell': Bell,
  'Eye': Eye,
  'Rocket': Rocket,
  'Play': Play,
  'PlayCircle': PlayCircle,
  'Timer': Timer,
  'CheckCircle': CheckCircle,
  'XCircle': XCircle,
  'Send': Send,
  'FileQuestion': FileQuestion,
  'Printer': Printer,
  'Copy': Copy,
  'LayoutDashboard': LayoutDashboard,
  'Layout': Layout,
  'Bot': Bot,
  'Gauge': Gauge,
  'Network': Network,
  'ChevronDown': ChevronDown,
  'ChevronUp': ChevronUp,
  'Mail': Mail,
  'Phone': Phone,
  'ScanBarcode': ScanBarcode,
  'ShoppingBasket': ShoppingBasket,
  'Terminal': Terminal,
  'FilePlus': FilePlus,
  'ExternalLink': ExternalLink,
  'Filter': Filter,
  'Badge': Badge,
  'Tablet': Tablet,
  'BarChart4': BarChart4,
  'Sparkles': Sparkles,
  'Database': Database,
  'Shield': Shield,
  'Route': Route,
  'File': File,
  'LayoutGrid': LayoutGrid,
  'Contact2': Contact2
}

export function getIcon(name: string | any) {
  if (typeof name !== 'string') return name
  return iconMap[name] || iconMap[name.toLowerCase()] || Info
}

export function getAllIconNames() {
  return Object.keys(iconMap).sort()
}
