
import { 
  Info, 
  List, 
  PlusCircle, 
  SearchX, 
  Plus, 
  Trash2, 
  Pencil, 
  MapPin, 
  Globe, 
  RefreshCw, 
  Tag, 
  PushPin, 
  Building2, 
  Folder, 
  BarChart3, 
  Calculator, 
  DollarSign, 
  CheckCircle2, 
  Package, 
  ClipboardList, 
  Settings, 
  X, 
  FileText, 
  Lightbulb, 
  Hash, 
  Zap, 
  Triangle, 
  Check, 
  Ban, 
  Search, 
  ArrowLeft, 
  ChevronRight, 
  CreditCard, 
  ShoppingCart, 
  Cpu, 
  FileEdit, 
  User, 
  UserPlus, 
  Key, 
  AlertTriangle, 
  Settings2, 
  Calendar, 
  GitFork, 
  Layers, 
  ClipboardCheck, 
  Truck, 
  History, 
  BadgeCheck, 
  CalendarOff,
  Sliders,
  Fingerprint,
  Link,
  CornerDownRight,
  PlusSquare,
  FolderOff,
  FilterX,
  AlertCircle,
  Users,
  Factory,
  UserCog,
  ShieldCheck,
  FolderTree
  } from 'lucide-vue-next'

  // Fallback mapping for material symbols to lucide icons
  const iconMap: Record<string, any> = {
  'info': Info,
  'list_alt': List,
  'add_circle': PlusCircle,
  'search_off': SearchX,
  'add': Plus,
  'delete': Trash2,
  'edit': Pencil,
  'location_on': MapPin,
  'public': Globe,
  'refresh': RefreshCw,
  'sell': Tag,
  'push_pin': PushPin,
  'corporate_fare': Building2,
  'folder': Folder,
  'bar_chart': BarChart3,
  'calculate': Calculator,
  'attach_money': DollarSign,
  'check_circle': CheckCircle2,
  'inventory_2': Package,
  'assignment': ClipboardList,
  'settings': Settings,
  'close': X,
  'description': FileText,
  'lightbulb': Lightbulb,
  'numbers': Hash,
  'bolt': Zap,
  'change_history': Triangle,
  'check': Check,
  'block': Ban,
  'search': Search,
  'arrow_back': ArrowLeft,
  'chevron_right': ChevronRight,
  'payments': CreditCard,
  'shopping_cart': ShoppingCart,
  'precision_manufacturing': Factory,
  'edit_note': FileEdit,
  'person': User,
  'person_add': UserPlus,
  'key': Key,
  'warning': AlertTriangle,
  'settings_suggest': Settings2,
  'calendar_today': Calendar,
  'account_tree': GitFork,
  'layers': Layers,
  'category': FolderTree,
  'fact_check': ClipboardCheck,
  'local_shipping': Truck,
  'history_edu': History,
  'badge': BadgeCheck,
  'event': Calendar,
  'event_note': Calendar,
  'event_busy': CalendarOff,
  'domain': Building2,
  'sync': RefreshCw,
  'tune': Sliders,
  'settings_input_component': Cpu,
  'branding_watermark': BadgeCheck,
  'notes': FileText,
  'fingerprint': Fingerprint,
  'link': Link,
  'subdirectory_arrow_right': CornerDownRight,
  'add_box': PlusSquare,
  'folder_off': FolderOff,
  'filter_alt_off': FilterX,
  'error': AlertCircle,
  'groups': Users,
  'manage_accounts': UserCog,
  'admin_panel_settings': ShieldCheck
  }

export function getIcon(name: string | any) {
  if (typeof name !== 'string') return name
  return iconMap[name] || Info // Info as fallback
}

export function getAllIconNames() {
  return Object.keys(iconMap).sort()
}
